version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  
  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
      args:
        database_url: "postgresql://program:test@postgres:5432/persons"
    ports:
      - "8000:8000"

volumes:
  db-data: